---
# tasks file for postgresql

- name: install the latest version of pgsql
  dnf:
    name: postgresql
    state: present

- name: install the latest version of pgsql-devel
  dnf:
    name: postgresql-devel
    state: present

- name: install the latest version of pgsql-devel
  dnf:
    name: gcc
    state: present

- name: install the latest version of python3-devel
  dnf:
    name: python3-devel
    state: present

- name: Install psql for Python 3 specifically, using the 'pip3' executable
  pip:
    name: psycopg2
    executable: pip3

- name: Install client for Python 3 specifically, using the 'pip3' executable
  pip:
    name: prometheus_client
    executable: pip3

- debug: msg="{{ hostvars['dummy_host']['transfer_var'] }}"
  tags: copy

- name: Set Fact for Python Template processing based on Dummy Host variable
  set_fact:
    steampipe_connect_string: "{{ hostvars['dummy_host']['transfer_var'] }}"
    cacheable: no
  tags: copy

- name: Copy OCI BV Python Template eu-zurich-1
  template:
    dest: /home/steampipe/py/pgsql-query-bv-zurich.py
    force: true
    src: pgsql-query-bv-zurich.py.j2
    mode: 0644
    owner: steampipe
    group: steampipe
  tags: steampipe

- name: Copy OCI CI Python Template eu-zurich-1
  template:
    dest: /home/steampipe/py/pgsql-query-ci-running-zurich.py
    force: true
    src: pgsql-query-ci-running-zurich.py.j2
    mode: 0644
    owner: steampipe
    group: steampipe
  tags: steampipe
