---
# tasks file for steampipe

- name: Ensure group 'steampipe' exists
  group:
    name: steampipe
    state: present
  tags: steampipe

- name: Add the user steampipe with a group of 'steampipe'
  user:
    name: steampipe
    comment: Steampipe User
    group: steampipe
  tags: steampipe

- name: create directory if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: steampipe
  loop:
    - /home/steampipe/sp
    - /home/steampipe/logs
    - /home/steampipe/config
    - /home/steampipe/plugins
    - /home/steampipe/.oci
    - /home/steampipe/sql
    - /home/steampipe/py
    - /home/steampipe/tmp
  tags:
    - steampipe
    - sql

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /home/steampipe/config/oci.spc
    state: absent
  tags: steampipe

- name: Pull Steampipe Docker Imagedocker
  community.docker.docker_image:
    name: turbot/steampipe
    source: pull
  tags: steampipe

- name: Create Steampipe Container and start
  community.docker.docker_container:
    name: steampipe
    image: turbot/steampipe
    detach: yes
    restart_policy: on-failure
    command: >
      service start --foreground
    mounts:
      - source: /home/steampipe/config
        target: /home/steampipe/.steampipe/config
        type: bind
    volumes:
      - "/home/steampipe/logs:/home/steampipe/.steampipe/logs"
      - "/home/steampipe/.oci:/home/steampipe/.oci"
    ports:
      - "0.0.0.0:9193:9193"
    container_default_behavior: no_defaults
  tags: steampipe
  
- name: Install OCI Plugin
  community.docker.docker_container_exec:
    container: steampipe
    command: /bin/bash -c "steampipe plugin install oci"
  tags: steampipe

- name: Copy OCI Steampipe template
  template:
    dest: /home/steampipe/config/oci.spc
    force: true
    src: etc-oci.spc.j2
    mode: 0644
    owner: steampipe
    group: steampipe
  tags: steampipe

- name: Copy OCI configuration files
  copy:
    src: "{{item}}"
    dest: "/home/steampipe/.oci"
    owner: steampipe
    group: steampipe
    mode: 0644
  loop:
    - config
  tags:
    - steampipe

- name: Get PG Connect String
  shell: docker exec -it steampipe steampipe service status | grep postgres | awk '{ sub(/^[ \t]+/, ""); print }'
  args:
    executable: /bin/bash
  register: steampipe_connect
  tags:
    - steampipe
    - copy

- debug: msg="{{ steampipe_connect.stdout }}"
  tags:
    - steampipe
    - copy

- name: Copy SQL files
  copy:
    src: "{{item}}"
    dest: "/home/steampipe/sql"
    owner: steampipe
    group: steampipe
    mode: 0644
  loop:
    - oci_bv_eu_frankfurt_1.sql
    - oci_bv_eu_zurich_1.sql
  tags:
    - steampipe

- name: Setting facts so that they will be persisted in the fact cache
  set_fact:
    steampipe_connect_string: "{{ steampipe_connect.stdout }}"
  tags: copy

- debug: msg="{{steampipe_connect_string}}"

- name: Register dummy host with variable to use it in next playbook
  add_host:
    name: "dummy_host"
    transfer_var: "{{ steampipe_connect_string }}"
  tags: copy
