# ---------------------------------------------------------------------------
# Name.......: configure-grafana/tasks/main.yml
# Author.....: Martin Berger (mbg) martin.x.berger@accenture.com
# Editor.....: Martin Berger
# Date.......: 2022.11.17
# Revision...:  
# Purpose....: Prepare directories and files for Grafana
# Notes......: 
# Reference..: 
# License....: Apache License Version 2.0, January 2004 as shown
#              at http://www.apache.org/licenses/
# ---------------------------------------------------------------------------

---

# - Configure Grafana -------------------------------------------------------
# - Create directories
# - Configure Prometheus as Data Source
# - Configure example dashboard
# - Enable port 3000 in firewall
# ---------------------------------------------------------------------------

- name: Create directories if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  loop:
    - /etc/grafana/provisioning/datasources
    - /etc/grafana/provisioning/notifiers
    - /etc/grafana/provisioning/plugins
    - /etc/grafana/provisioning/dashboards
    - /etc/grafana/provisioning/alerting
  tags: configure-grafana

- name: Copy Grafana Data Source Configuration
  template:
    dest: /etc/grafana/provisioning/datasources/datasource.yml
    force: true
    src: grafana/datasource.yml.j2
    mode: 0644
  tags: configure-grafana

- name: Copy Grafana Data Source Dashboard General Configuration
  template:
    dest: /etc/grafana/provisioning/dashboards/dashboard.yml
    force: true
    src: grafana/dashboard.yml.j2
    mode: 0644
  tags: configure-grafana

- name: Copy Grafana Data Source Example Dashboard
  template:
    dest: /etc/grafana/provisioning/dashboards/dashboard-small.json
    force: true
    src: grafana/dashboard-small.json.j2
    mode: 0644
  tags: configure-grafana

- name: Enable port 3000 in firewall rules
  firewalld:
    port: 3000/tcp
    state: enabled
  tags: configure-grafana