---
- name: Install OCI Monitoring
  hosts: monitoring
  become: yes
  roles:
    - configure-grafana
    - configure-prometheus
    - configure-pushgateway
    - configure-psql
    - configure-docker
    - run-docker-compose
    - configure-steampipe

