---
- name: Install OCI Monitoring
  hosts: monitoring
  become: yes
  roles:
    - prepare
    - docker
    - docker-compose
    #- steampipe
    #- postgresql
    #- prometheus-pre
    #- grafana-pre
    #- pushgateway-pre
