---
# tasks file for prepare-docker-compose
- name: create directory if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  loop:
    - /etc/docker
  tags: compose

- name: Grafana Data Source Configuration
  template:
    dest: /etc/docker/docker-compose.yml
    force: true
    src: docker-compose/docker-compose.yml.j2
    mode: 0644
  tags: compose
