# tasks file for steampipe

- name: Ensure group 'steampipe' exists
  group:
    name: steampipe
    state: present
  tags: steampipe

- name: Add the user steampipe with a group of 'steampipe'
  user:
    name: steampipe
    comment: Steampipe User
    group: steampipe
  tags: steampipe

- name: create directory if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: steampipe
  loop:
    - /home/steampipe/sp
    - /home/steampipe/logs
    - /home/steampipe/config
    - /home/steampipe/plugins
    - /home/steampipe/.oci
    - /home/steampipe/sql
    - /home/steampipe/py
    - /home/steampipe/tmp
  tags:
    - steampipe
    - sql

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /home/steampipe/config/oci.spc
    state: absent
  tags: steampipe

- name: Copy OCI Steampipe template
  template:
    dest: /home/steampipe/config/oci.spc
    force: true
    src: steampipe/etc-oci.spc.j2
    mode: 0644
    owner: steampipe
    group: steampipe
  tags: steampipe

- name: Copy OCI configuration files
  copy:
    src: "steampipe/{{item}}"
    dest: "/home/steampipe/.oci"
    owner: steampipe
    group: steampipe
    mode: 0644
  loop:
    - config
  tags:
    - steampipe