# ---------------------------------------------------------------------------
# Name.......: configure-prometheus/tasks/main.yml
# Author.....: Martin Berger (mbg) martin.x.berger@accenture.com
# Editor.....: Martin Berger
# Date.......: 2022.11.17
# Revision...:  
# Purpose....: Prepare directories and files for Prometheus
# Notes......: 
# Reference..: 
# License....: Apache License Version 2.0, January 2004 as shown
#              at http://www.apache.org/licenses/
# ---------------------------------------------------------------------------

---

# - Configure Prometheus -------------------------------------------------------
# - Verify user and group
# - Create directories
# - Copy configuration file
# - Enable port 9090 in firewall
# ---------------------------------------------------------------------------

- name: Ensure group 'prometheus' exists
  group:
    name: prometheus
    state: present
  tags: configure-prometheus

- name: Add the user prometheus with a group of 'prometheus'
  user:
    name: prometheus
    comment: Prometheus User
    group: prometheus
  tags: configure-prometheus

- name: Create directories if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0775
  loop:
    - /etc/prometheus
    - /home/prometheus/data
  tags: configure-prometheus

- name: Copy Prometheus configuration file
  template:
    dest: /etc/prometheus/prometheus.yml
    force: true
    src: prometheus/etc-prometheus-yml.j2
    mode: 0644
    owner: prometheus
    group: prometheus
  tags: configure-prometheus

- name: Enable port 9090 in firewall rules
  firewalld:
    port: 9090/tcp
    state: enabled
  tags: configure-prometheus
