# tasks file for config-postgresql

- debug: msg="{{ hostvars['dummy_host']['transfer_var'] }}"
  tags: copy

- name: Set Fact for Python Template processing based on Dummy Host variable
  set_fact:
    steampipe_connect_string: "{{ hostvars['dummy_host']['transfer_var'] }}"
    cacheable: no
  tags: copy

- name: Copy OCI BV Python Template eu-zurich-1
  template:
    dest: /home/steampipe/py/pgsql-example-block-volume-summary.py
    force: true
    src: postgresql/pgsql-example-block-volume-summary.py.j2
    mode: 0644
    owner: steampipe
    group: steampipe
  tags: steampipe

- name: Copy OCI CI Python Template eu-zurich-1
  template:
    dest: /home/steampipe/py/pgsql-example-compute-instance-running.py
    force: true
    src: postgresql/pgsql-example-compute-instance-running.py.j2
    mode: 0644
    owner: steampipe
    group: steampipe
  tags: steampipe