# tasks file for config-steampipe
- name: Install OCI Plugin
  community.docker.docker_container_exec:
    container: steampipe
    command: /bin/bash -c "steampipe plugin install oci"


- name: Get PG Connect String
  shell: docker exec --tty steampipe steampipe service status --show-password | grep postgres
  args:
    executable: /bin/bash
  register: steampipe_connect_full

- name: Setting facts so that they will be persisted in the fact cache
  set_fact:
          steampipe_connect_string: "{{ steampipe_connect_full.stdout[22:90] }}"
  tags: copy

- debug: msg="{{steampipe_connect_string}}"

- name: Register dummy host with variable to use it in next playbook
  add_host:
    name: "dummy_host"
    transfer_var: "{{ steampipe_connect_string }}"
  tags: copy

- name: Remove default file (delete file)
  ansible.builtin.file:
    path: /home/steampipe/config/oci.spc
    state: absent
  tags: steampipe

- name: Copy OCI Steampipe template
  template:
    dest: /home/steampipe/config/oci.spc
    force: true
    src: steampipe/etc-oci.spc.j2
    mode: 0644
    owner: steampipe
    group: steampipe
  tags: steampipe